import Head from 'next/head'
import Feed from '../components/Feed'
import Sidebar from '../components/Sidebar'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      
      <main className='bg-black  min-h-screen flex max-w-[1500px] mx-auto'>
        {/* side bar  */}
        <Sidebar />
        {/* feed  */}
        <Feed />
        {/* Widgets  */}

        {/* model  */}
      </main>
    </div>
  )
}
